### ISSUE TITLE
Not working after Wotlk 3.4.1 Ulduar Patch

### ISSUE THREAD

**Issue by Himitsu1990** [azuraji/MonkeyQuest#1]
The errors I get:

Message: Interface/AddOns/MonkeyLibrary/MonkeyLibrary.lua:39: Usage: self:SetFont(fontFile, height, flags)
Time: Thu Jan 19 14:53:04 2023
Count: 1
Stack: Interface/AddOns/MonkeyLibrary/MonkeyLibrary.lua:39: Usage: self:SetFont(fontFile, height, flags)
Locals: 

Message: MonkeyQuestTitleText:SetText(): Font not set
Time: Thu Jan 19 14:53:40 2023
Count: 251
Stack: MonkeyQuestTitleText:SetText(): Font not set
Locals: 

Message: ...erface/AddOns/MonkeyQuestLog/MonkeyQuestLogFrame.lua:17: attempt to call global 'MonkeyLib_DebugMsg' (a nil value)
Time: Thu Jan 19 14:53:04 2023
Count: 1
Stack: ...erface/AddOns/MonkeyQuestLog/MonkeyQuestLogFrame.lua:17: attempt to call global 'MonkeyLib_DebugMsg' (a nil value)
Locals: 

Message: Interface/AddOns/MonkeyBuddy/MonkeyBuddy.lua:431: attempt to call global 'MonkeyLib_ColourStrToARGB' (a nil value)
Time: Thu Jan 19 14:53:09 2023
Count: 1
Stack: Interface/AddOns/MonkeyBuddy/MonkeyBuddy.lua:431: attempt to call global 'MonkeyLib_ColourStrToARGB' (a nil value)
Locals: 

Message: Interface/AddOns/MonkeySpeed/MonkeySpeedInit.lua:24: attempt to call method 'SetMinResize' (a nil value)
Time: Thu Jan 19 14:53:09 2023
Count: 1
Stack: Interface/AddOns/MonkeySpeed/MonkeySpeedInit.lua:24: attempt to call method 'SetMinResize' (a nil value)
Locals:

**Comment by azuraji** [comment]
I have no intentions to make the addon work for WoW Classic as I don't play that myself. Apologies.
